### ISSUE TITLE
Renaming Ptt-layer to Router.

### ISSUE THREAD

**Issue by chhsiao1981** [ailabstw/go-pttai-core#6]
The original purpose for "Ptt-layer" is to let the entities be able to access some common-features.

Currently "Ptt-layer" includes the follow features:

1. Given a packet from entity A, able to send to the other node and let the other node know that the packet belongs to A and pass to A.
2. Let the entities be able to add-peer (Used only in Me and Friend)
3. A general flow to join specific entity.
4. Access MyInfo and Sign oplog.

After discussion, "Router" looks more suitable to the current use in ptt-layer.

**Comment by poga** [comment]
fixed by https://github.com/ailabstw/go-pttai-core/commit/92890cac1eea935842be2e4a1c6e80529f85bcf9
